app/urls.py
from django.urls import path
from  .views import CustomLoginView, send_welcome_email
from . import views
from  .views import CustomRegisterView
from django.contrib.auth.views import LogoutView
from django.views.generic.base import RedirectView






urlpatterns = [

     path("login/",CustomLoginView.as_view(),name="login"),
     path('', views.index, name="home"),
     path("register/",CustomRegisterView.as_view(),name="register"),
     path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
     path('sen-welcome/', send_welcome_email, name='send_welcome_email'),
     path('accounts/login', CustomLoginView.as_view(), name='login'),
     path('login/', RedirectView.as_view(url='/accounts/login'), name='login'),
     path('login/', RedirectView.as_view(url='/admin'), name='login'),
     
     path('main/', views.main, name='main'),
     path('watch/', views.watch, name='watch'),
     path('backend/', views.backend, name="endd"),
     path('new/', views.new),
     path('policy/', views.policy),
     path('backend/', views.backend, name="endd"),
     path('about/', views.about),
     path('comedy/', views.comedy, name="comedy"),
     path('africa/', views.africa, name="africa"),
     path('upcoming/', views.upcoming),
]

checkout/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("ShowCheckOut/", ShowCheckOut, name="ShowCheckOut"),
    path("CheckOut/", CheckOut, name="CheckOut"),  

]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', RedirectView.as_view(url='/admin'),name="admin"),
    path("", include("app.urls")),
    path('verification/', include('verify_email.urls')),
    path('',include('django.contrib.auth.urls')),
    path("", include("product.urls")),
    path("", include("cart.urls")),
    path('app/', include ('app.urls')),
    path('contact/', include ('contact.urls')),
    path("", include('checkout.urls')),
    path("", include('favorite.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from custom_user.models import User
from django.db import models

# Create your models here.

class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.CharField(max_length=50000, null=True)
    cart = models.CharField(max_length=200000, null=True)
    customer_code = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    first_name = models.CharField(max_length=250)
    surname = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    door_to_door_fee = models.FloatField()
    price = models.FloatField()
    

    def __str__(self):
        return str(self.first_name) + " " + str(self.last_name)

  

checkout/forms.py
from django import forms
from .models import Checkout


# creating a form
class CheckoutForm(forms.ModelForm):

	# create meta class
	class Meta:
		# specify model to be used
		model = Checkout

		# specify fields to be used
		fields = [
            "email",
			"first_name",
            "surname",
			"last_name",
            "address",
            ]

		
		

checkout/views.py
from django.shortcuts import render
import random
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from cart.models import Cart
from product.models import Product
from .models import Checkout
from .forms import CheckoutForm


def ShowCheckOut(request):
    if request.user.is_authenticated:

        cart = Cart.objects.filter(user=request.user)
        prod = []
        car = []
        for data in cart:
            print(data.product)
            products = Product.objects.filter(name=data.product)
            for productData in products:
                prod.append(productData.name) 
            car.append(data.quantity)
        print(prod)
                
                
                
        form = CheckoutForm
        # MyQuantityRange = ""

        totall = sum(item.Total_costs() for item in cart)

        # for cartdat in cart:
        #     MyQuantityRange = range(cartdat.product.quantity)
        # print(MyQuantityRange)
        
        print(str(random.randint(200,757)))
       

        
        if request.method == "POST":
            form = CheckoutForm(request.POST)
            if form.is_valid():
                newform = form.save(commit=False)
                newform.user = request.user
                newform.product = prod
                newform.cart = car
                newform.door_to_door_fee = 40.5
                newform.shipping = 40.5
                newform.price = totall + 40.5 + 40.5
                newform.customer_code = str(request.user) + str(random.randint(200007647,7577880058))
                newform.save()
                return redirect("product_list")
            else:
               form = CheckoutForm()
    
        context = {"cart": cart, "totall": totall, "form":form}
        return render(request, "checkout/checkout.html", context)

    return render(request, "checkout/checkout.html", { })


def CheckOut(request):
    if request.user.is_authenticated:
        if request.method == "POST":
           
           
            # first_name = request.POST['first_name']
            # last_name = request.POST['last_name']
            # surname = request.POST['surname']
            # user = request.user
            
            # customer_code = str(request.user) + str(random.randint(200007647,7577880058))
            # email = request.POST['email']
            # address = request.POST['address']
            # shipping = 100.55
            # door_to_door_fee = 100.74
            # price =  shipping + door_to_door_fee +1000

            # myDATA = Checkout(
            #       first_name = first_name, 
            #       last_name = last_name,
            #       surname = surname,
            #       user = user,
            #       customer_code =customer_code,
            #       email=email,
            #       address=address,
            #       shipping = shipping,
            #        door_to_door_fee= door_to_door_fee,
            #        price = price
            #                   )
            # myDATA.save()
            # form = CheckoutForm(request.POST)
            # form.save()
            return HttpResponseRedirect(request.META.get("HTTP_REFERER")) 
              

checkout/templates/checkout/checkout.html
<!doctype html>
{% extends "app/layout.html" %}
{% load static %}
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Checkout Page</title>
 
  </head>
  <body>

{% block content%}
<br>
<br>
<br>
{% comment %} <div class="container">
  <main>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">3</span>
        </h4>
        <ul class="list-group mb-3">

          {% for cart in cart %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{cart.product.name}}</h6>
              <img src="{{cart.product.image.url}}" width="15%">
            </div>
            <span class="text-muted">${{cart.product.price}}</span>
          </li>
          {% endfor %}
         

          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
       
        <strong>{{totall}}</strong>
          </li>
        </ul>

        <form class="card p-2" action="">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code" value="">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>



        <form method="post">
          {% csrf_token %}
            {{form.as_p}}
          <hr class="my-4">
           <button class="w-100 btn btn-primary btn-lg" type="submit">Place Order</button>
        </form>

      </div>
    </div>
  </main>
</div> {% endcomment %}


<br>
<br>
<br>
<br>
<style>
.checkoutLayout{
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 30px;
}

.checkoutLayout .right{
  background-color: #5358b3;
  border-radius: 20px;
  padding: 10px;
  color: #fff;
}

.checkoutLayout .listt img{
  height: 70px;
}

.checkoutLayout .right .formm{
  display: grid;
  grid-template-columns: repeat(1, 1fr);
  gap: 15px;
  border-button: 1px solid #7a7fe2;
  padding-button: 20px;
}

.checkoutLayout .formm .group:nth-child(-n+5){
  grid-column-start: 1;
  grid-column-end: 3;
}

.checkoutLayout .formm input, .checkoutLayout .formm select{
  width: 100%;
  padding: 10px 30px;
  box-sizing: border-box;
  border-radius: 20px;
  border: none;
  background-color: #6a6fce;
  color: #fff;
}

.checkoutLayout .roww{
  display: flex;
  justify-content: space-between;
  align-item: center;
  margin-top: 10px;
}

.checkoutLayout .roww div:nth child(2){
  font-weight: bold;
  font-size: x-large;
}

.buttonCheckout{
  width: 100%;
  height: 40px;
  boder: none;
  border-radius: 20px;
  margin-top: 20px;
  font-weight: bold;
  color: #fff;
  background-color: #49d8b9;
}

.returnCart h1{
  border-top: 1px solid #eee;
}

.returnCart .listt .item img{
}

.returnCart .item{
  display: flex;
  align-items: center;
  gap: 45px;
  margin-button: 30px;
  padding: 0 10px;
  box-shadow: 0 10px 20px #555;
  border-radius: 20px;
}

.returnCart .item .names, 
.returnCart .item returnPrice{
  font-size: x-large;
  font-weight: bold;
}
.returnCart a{
  color: white;
  font-size: 20px;
}

.returnCart a:hover{
  color: #ca9f13,
}

</style>  
<div class="cont">
  <div class="checkoutLayout">
    <div class="returnCart">
      <a href="/product_list">Keep Showping</a>
      <br>
      <br>
      <h1>List Product In Cart</h1>
      <br>
      {% for cart in cart %}
      <div class="listt">
        <div class="item">
          <img src="{{cart.product.image.url}}">
        <div class="infoo">
          <div class="names">{{cart.product.name}}</div>
          <a href="/Delete_Cart/{{cart.product.id}}" style="color: red; font-size: 17px">Remove</a>
          </div>
        <div class="Quantity">{{ cart.quantity}}</div>
        <div class="returnPrice">${{cart.Total_cost }}</div>
        </div>
        <br>
        <br>
      </div>
      {% endfor %}
      
    </div>
      <div class="right">
        <h1>Billing / address</h1>
        <div class="formm">
          <div class="group">
            <form method="POST">
              {% csrf_token %}
              <label for="id_email">Email:</label>
              <input type="email" name="email" maxlength="250" required id="id_email">
          </div>
          <div class="group">
            <label for="id_first_name">First name:</label>
    <input type="text" name="first_name" maxlength="250" required id="id_first_name">
          </div>
          <div class="group">
            <label for="id_surname">Surname:</label>
    <input type="text" name="surname" maxlength="250" required id="id_surname">
    
          </div>
          <div class="group">
            <label for="id_last_name">Last name:</label>
            <input type="text" name="last_name" maxlength="250" required id="id_last_name">
          </div>
          <div class="group">
            <label for="id_address">Address:</label>
            <input type="text" name="address" maxlength="250" required id="id_address">
         </div>
          <div class="group">
            <label for="id_county">County</label>
            <select name="" required id="id_county">
              <option value="">Choose..</option>
              <option value="london">Ghana</option>
            </select>
          </div>
          <div class="group">
            <label for="id_city">City</label>
            <select name="" required id="id_city">
              <option value="">Choose..</option>
              <option value="london">Kumasi</option>
            </select>
          </div>
        </div>
        <div class="return">
          <div class="roww">
            <div>Total Quantity</div>
            <div class="totalQuantity">{{ request.session.cart }}</div>
          </div>
          <div class="roww">
            <div>Total Price</div>
            <div class="totalPrice">{{totall}}</div>
          </div>
        </div>
        <button class="buttonCheckout" type="submit">
          Place Order
        </button>
      </form>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock%}

  </body>
</html>